header-from: ./.config/header.md

version: ""

formatter: markdown table

name:  terraform-aws-lambda-redis-slowlog-to-cw-logs

content: |-
  {{ .Header }}

  # terraform-aws-lambda-redis-slowlog-to-cw-logs

  GitHub: [StratusGrid/terraform-aws-lambda-redis-slowlog-to-cw-logs](https://github.com/StratusGrid/terraform-aws-lambda-redis-slowlog-to-cw-logs)

  This module will deploy a lambda function which will poll all redis_targets defined according to the schedule defined with schedule_expression

  ### Areas Needing Improvement:
  - Add a timeout for redis to connect (currently it just stays open till the function times out)
  - Add server name as key in log object (can be used for metrics and filtering more easily this way)
  - Make logic for checking and selecting logs group better
  - Make logic for checking and selecting logs stream better
  - Organize and segment code better
  - Better error handling
  
  ## Example Usage:
  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  ---
  ### Example Logs Enties:
  ```hcl
  {{ include "examples/example2.tfnot" }}
  ```
  ---
  ### Example Logs Insights Queries:
  Count of slow logs per minute:
  ```
  stats count(*) as count by bin(1m)
  ```
  Count of slowlog entries per unique query:
  ```
  stats count(*) as count by cmdArray.0,cmdArray.1
  ```
  
  Count of slowlog entries per minute for a specific key:
  ```
  filter cmdArray.1 like /my-key-name/
  | stats count(*) as count by bin (60s)
  ```
  
  Sort slowlog entries by duration, slowest at the top:
  ```
  sort by duration desc
  ```
  
  Average duration of requests per key for time period:
  ```
  stats avg(duration) as avg by cmdArray.0,cmdArray.1 | sort by avg desc
  ```
  
  Total time spent in slowlog entries for all servers for time period by key:
  ```
  stats sum(duration) as sum by cmdArray.0,cmdArray.1 | sort by sum desc
  ```
  
  Total time spent per monitored server for time period:
  ```
  stats sum(duration) by @logStream
  ```

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - header
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
